import Head from 'next/head';
import styles from '../styles/Home.module.css';
//import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();

  if (session) {
    return (

      <div className={styles.container}>
        <Head>
          <title>Wizard</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Youtube Music Playlist Wizard
          </h1>

          <p className={styles.description}>
            music playlists on youtube made easy!
          </p>

          <button className={styles.title} onClick={() => signOut()}>Sign Out</button>

        </main>        
      </div>
    );
  }

  return (
    <div className={styles.container}>
        <Head>
          <title>Wizard</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Youtube Music Playlist Wizard
          </h1>

          <p className={styles.description}>
            music playlists on youtube made easy!
          </p>

          <button className={styles.title} onClick={() => signIn('google', {callbackUrl: '/playlistRequest'})}>Get Started</button>

        </main>
    </div>
  );
}